vector db endpoints * configs and default attributes + indexes * separate collection creation setup * fix -> database metadata fix on collection creation

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -89,11 +89,13 @@ services:
       - ./public:/usr/src/code/public
       - ./src:/usr/src/code/src
       - ./dev:/usr/src/code/dev
+      - .vendor:/usr/src/code/dev
 
     depends_on:
       - ${_APP_DB_HOST:-mongodb}
       - postgresql
       - redis
+      - ollama
       # - clamav
     entrypoint:
       - php
@@ -138,6 +140,12 @@ services:
       - _APP_DB_SCHEMA
       - _APP_DB_USER
       - _APP_DB_PASS
+      - _APP_DB_ADAPTER_VECTORDB
+      - _APP_DB_HOST_VECTORDB
+      - _APP_DB_PORT_VECTORDB
+      - _APP_DB_SCHEMA_VECTORDB
+      - _APP_DB_USER_VECTORDB
+      - _APP_DB_PASS_VECTORDB
       - _APP_SMTP_HOST
       - _APP_SMTP_PORT
       - _APP_SMTP_SECURE
@@ -272,6 +280,7 @@ services:
       - ${_APP_DB_HOST:-mongodb}
       - postgresql
       - redis
+      - ollama
     environment:
       - _APP_ENV
       - _APP_WORKER_PER_CORE
@@ -288,6 +297,12 @@ services:
       - _APP_DB_SCHEMA
       - _APP_DB_USER
       - _APP_DB_PASS
+      - _APP_DB_ADAPTER_VECTORDB
+      - _APP_DB_HOST_VECTORDB
+      - _APP_DB_PORT_VECTORDB
+      - _APP_DB_SCHEMA_VECTORDB
+      - _APP_DB_USER_VECTORDB
+      - _APP_DB_PASS_VECTORDB
       - _APP_USAGE_STATS
       - _APP_LOGGING_CONFIG
       - _APP_DATABASE_SHARED_TABLES
@@ -306,6 +321,7 @@ services:
       - redis
       - ${_APP_DB_HOST:-mongodb}
       - postgresql
+      - ollama
     environment:
       - _APP_ENV
       - _APP_WORKER_PER_CORE
@@ -339,6 +355,7 @@ services:
       - postgresql
       - request-catcher-sms
       - request-catcher-webhook
+      - ollama
     environment:
       - _APP_ENV
       - _APP_WORKER_PER_CORE
@@ -369,6 +386,7 @@ services:
       - redis
       - ${_APP_DB_HOST:-mongodb}
       - postgresql
+      - ollama
     volumes:
       - appwrite-uploads:/storage/uploads:rw
       - appwrite-cache:/storage/cache:rw
@@ -437,6 +455,7 @@ services:
       - redis
       - ${_APP_DB_HOST:-mongodb}
       - postgresql
+      - ollama
     environment:
       - _APP_ENV
       - _APP_WORKER_PER_CORE
@@ -451,6 +470,12 @@ services:
       - _APP_DB_SCHEMA
       - _APP_DB_USER
       - _APP_DB_PASS
+      - _APP_DB_ADAPTER_VECTORDB
+      - _APP_DB_HOST_VECTORDB
+      - _APP_DB_PORT_VECTORDB
+      - _APP_DB_SCHEMA_VECTORDB
+      - _APP_DB_USER_VECTORDB
+      - _APP_DB_PASS_VECTORDB
       - _APP_LOGGING_CONFIG
       - _APP_WORKERS_NUM
       - _APP_QUEUE_NAME
@@ -474,6 +499,7 @@ services:
       - redis
       - ${_APP_DB_HOST:-mongodb}
       - postgresql
+      - ollama
     environment:
       - _APP_BROWSER_HOST
       - _APP_ENV
@@ -543,6 +569,7 @@ services:
       - redis
       - ${_APP_DB_HOST:-mongodb}
       - postgresql
+      - ollama
     volumes:
       - appwrite-config:/storage/config:rw
       - appwrite-certificates:/storage/certificates:rw
@@ -588,6 +615,7 @@ services:
       - ${_APP_DB_HOST:-mongodb}
       - postgresql
       - openruntimes-executor
+      - ollama
     environment:
       - _APP_ENV
       - _APP_WORKER_PER_CORE
@@ -725,6 +753,7 @@ services:
     depends_on:
       - ${_APP_DB_HOST:-mongodb}
       - postgresql
+      - ollama
     environment:
       - _APP_ENV
       - _APP_WORKER_PER_CORE
@@ -809,6 +838,7 @@ services:
       - redis
       - ${_APP_DB_HOST:-mongodb}
       - postgresql
+      - ollama
     environment:
       - _APP_ENV
       - _APP_WORKER_PER_CORE
@@ -842,6 +872,7 @@ services:
       - redis
       - ${_APP_DB_HOST:-mongodb}
       - postgresql
+      - ollama
     environment:
       - _APP_ENV
       - _APP_WORKER_PER_CORE
@@ -875,6 +906,7 @@ services:
       - redis
       - ${_APP_DB_HOST:-mongodb}
       - postgresql
+      - ollama
     environment:
       - _APP_ENV
       - _APP_WORKER_PER_CORE
@@ -908,6 +940,7 @@ services:
       - ${_APP_DB_HOST:-mongodb}
       - postgresql
       - redis
+      - ollama
     environment:
       - _APP_ENV
       - _APP_WORKER_PER_CORE
@@ -938,6 +971,7 @@ services:
       - ${_APP_DB_HOST:-mongodb}
       - postgresql
       - redis
+      - ollama
     environment:
       - _APP_ENV
       - _APP_WORKER_PER_CORE
@@ -967,6 +1001,7 @@ services:
       - ${_APP_DB_HOST:-mongodb}
       - postgresql
       - redis
+      - ollama
     environment:
       - _APP_ENV
       - _APP_WORKER_PER_CORE
@@ -1089,55 +1124,55 @@ services:
       - MARIADB_AUTO_UPGRADE=1
     command: "mysqld --innodb-flush-method=fsync"
 
-  mongodb:
-    image: mongo:8.0.10
-    container_name: appwrite-mongodb
-    <<: *x-logging
-    networks:
-      - appwrite
-    volumes:
-      - appwrite-mongodb:/data/db
-      - appwrite-mongodb-keyfile:/data/keyfile
-      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
-      - ./mongo-entrypoint.sh:/mongo-entrypoint.sh:ro
-    ports:
-      - "27017:27017"
-    environment:
-      - MONGO_INITDB_ROOT_USERNAME=root
-      - MONGO_INITDB_ROOT_PASSWORD=${_APP_DB_ROOT_PASS}
-      - MONGO_INITDB_DATABASE=${_APP_DB_SCHEMA}
-      - MONGO_INITDB_USERNAME=${_APP_DB_USER}
-      - MONGO_INITDB_PASSWORD=${_APP_DB_PASS}
-    entrypoint: ["/bin/bash", "/mongo-entrypoint.sh"]
-    healthcheck:
-      test: |
-        bash -c "
-          if mongosh -u root -p ${_APP_DB_ROOT_PASS} --authenticationDatabase admin --quiet --eval 'rs.status().ok' 2>/dev/null | grep -q 1; then
-            exit 0
-          else
-            mongosh -u root -p ${_APP_DB_ROOT_PASS} --authenticationDatabase admin --quiet --eval \"
-              rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'appwrite-mongodb:27017'}]})
-            \" 2>/dev/null || exit 1
-          fi
-        "
-      interval: 10s
-      timeout: 10s
-      retries: 10
-      start_period: 30s
+  # mongodb:
+  #   image: mongo:8.0.10
+  #   container_name: appwrite-mongodb
+  #   <<: *x-logging
+  #   networks:
+  #     - appwrite
+  #   volumes:
+  #     - appwrite-mongodb:/data/db
+  #     - appwrite-mongodb-keyfile:/data/keyfile
+  #     - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
+  #     - ./mongo-entrypoint.sh:/mongo-entrypoint.sh:ro
+  #   ports:
+  #     - "27017:27017"
+  #   environment:
+  #     - MONGO_INITDB_ROOT_USERNAME=root
+  #     - MONGO_INITDB_ROOT_PASSWORD=${_APP_DB_ROOT_PASS}
+  #     - MONGO_INITDB_DATABASE=${_APP_DB_SCHEMA}
+  #     - MONGO_INITDB_USERNAME=${_APP_DB_USER}
+  #     - MONGO_INITDB_PASSWORD=${_APP_DB_PASS}
+  #   entrypoint: ["/bin/bash", "/mongo-entrypoint.sh"]
+  #   healthcheck:
+  #     test: |
+  #       bash -c "
+  #         if mongosh -u root -p ${_APP_DB_ROOT_PASS} --authenticationDatabase admin --quiet --eval 'rs.status().ok' 2>/dev/null | grep -q 1; then
+  #           exit 0
+  #         else
+  #           mongosh -u root -p ${_APP_DB_ROOT_PASS} --authenticationDatabase admin --quiet --eval \"
+  #             rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'appwrite-mongodb:27017'}]})
+  #           \" 2>/dev/null || exit 1
+  #         fi
+  #       "
+  #     interval: 10s
+  #     timeout: 10s
+  #     retries: 10
+  #     start_period: 30s
 
-  appwrite-mongo-express:
-    image: mongo-express
-    container_name: appwrite-mongo-express
-    networks:
-      - appwrite
-    ports:
-      - "8082:8081"
-    environment:
-      ME_CONFIG_MONGODB_URL: "mongodb://root:${_APP_DB_ROOT_PASS}@appwrite-mongodb:27017/?replicaSet=rs0&directConnection=true"
-      ME_CONFIG_BASICAUTH_USERNAME: ${_APP_DB_USER}
-      ME_CONFIG_BASICAUTH_PASSWORD: ${_APP_DB_PASS}
-    depends_on:
-      - mongodb
+  # appwrite-mongo-express:
+  #   image: mongo-express
+  #   container_name: appwrite-mongo-express
+  #   networks:
+  #     - appwrite
+  #   ports:
+  #     - "8082:8081"
+  #   environment:
+  #     ME_CONFIG_MONGODB_URL: "mongodb://root:${_APP_DB_ROOT_PASS}@appwrite-mongodb:27017/?replicaSet=rs0&directConnection=true"
+  #     ME_CONFIG_BASICAUTH_USERNAME: ${_APP_DB_USER}
+  #     ME_CONFIG_BASICAUTH_PASSWORD: ${_APP_DB_PASS}
+  #   depends_on:
+  #     - mongodb
 
 
   postgresql:
@@ -1157,6 +1192,22 @@ services:
       - POSTGRES_USER=${_APP_DB_USER}
       - POSTGRES_PASSWORD=${_APP_DB_PASS}
     command: "postgres"
+
+  ollama:
+    build: 
+      context: .
+      dockerfile: ollama.dockerfile
+    container_name: ollama
+    ports:
+      - "11434:11434"
+    restart: unless-stopped
+    # persistent for caching models across restarts and preloading
+    volumes:
+      - ollama_models:/root/.ollama
+    environment:
+      - MODELS=${OLLAMA_MODELS:-embeddinggemma}
+      # duration to keep model in memory
+      - OLLAMA_KEEP_ALIVE=24h
 
   redis:
     image: redis:7.2.4-alpine
@@ -1256,8 +1307,9 @@ networks:
 
 volumes:
   appwrite-mariadb:
-  appwrite-mongodb:
-  appwrite-mongodb-keyfile:
+  # appwrite-mongodb:
+  # appwrite-mongodb-keyfile:
+  appwrite-postgresql:
   appwrite-redis:
   appwrite-cache:
   appwrite-uploads:
@@ -1267,3 +1319,4 @@ volumes:
   appwrite-sites:
   appwrite-builds:
   appwrite-config:
+  ollama_models:
