Improve tests OPR setup

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -170,6 +170,29 @@ jobs:
           docker compose up -d
           sleep 30
 
+      - name: Wait for Open Runtimes
+        run: |
+          max_attempts=25
+          delay=5
+          attempt=0
+          success=0
+          while [ $attempt -lt $max_attempts ]; do
+            response=$(docker compose exec appwrite sh -c "curl -I \$_APP_EXECUTOR_HOST/health -H \"Authorization: Bearer \$_APP_EXECUTOR_SECRET\"")
+            if echo $response | grep -q '200 OK'; then
+              success=1
+              break
+            else
+               echo "Health check failed, retrying..."
+               sleep $delay
+               ((attempt++))
+            fi
+          done
+
+          if [ $success -eq 0 ]; then
+            echo "Failed to start Open Runtimes"
+            exit 1
+          fi
+
       - name: Run ${{ matrix.service }} tests with Project table mode
         run: |
           echo "Using project tables"
@@ -231,7 +254,7 @@ jobs:
         run: |
           docker load --input /tmp/${{ env.IMAGE }}.tar
           docker compose up -d
-          sleep 60
+          sleep 30
 
       - name: Run ${{ matrix.service }} tests with ${{ matrix.tables-mode }} table mode
         run: |
@@ -244,9 +267,6 @@ jobs:
             export _APP_DATABASE_SHARED_TABLES=database_db_main
             export _APP_DATABASE_SHARED_TABLES_V1=
           fi
-
-          echo 'Sleep 1 minute, as temporary fix for v4rc executor startup (image pulling)'
-          sleep 60
       
           docker compose exec -T \
             -e _APP_DATABASE_SHARED_TABLES \
