Fix tests

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -172,26 +172,29 @@ jobs:
 
       - name: Wait for Open Runtimes
         run: |
-          max_attempts=25
-          delay=5
+          max_attempts=180
           attempt=0
           success=0
           while [ $attempt -lt $max_attempts ]; do
-            response=$(command "docker compose exec appwrite sh -c \"curl -I \$_APP_EXECUTOR_HOST/health -H \\"Authorization: Bearer \$_APP_EXECUTOR_SECRET\\"\")" || echo '0')
-            if echo $response | grep -q '200 OK'; then
-              success=1
-              break
-            else
-               echo "Health check failed, retrying..."
-               sleep $delay
-               ((attempt++))
-            fi
+              command="curl -s \$_APP_EXECUTOR_HOST/health -H \"Authorization: Bearer \$_APP_EXECUTOR_SECRET\""
+              response=$(docker compose exec appwrite sh -c "$command")
+
+              if [[ $response == *"runtimes"* ]]; then
+                  success=1
+                  break
+              else
+                  echo "Health check failed, retrying..."
+                  sleep 1
+                  ((attempt++))
+              fi
           done
 
           if [ $success -eq 0 ]; then
-            echo "Failed to start Open Runtimes"
-            exit 1
+              echo "Failed to start Open Runtimes executor"
+              exit 1
           fi
+
+          echo "Open Runtimes executor started"
 
       - name: Run ${{ matrix.service }} tests with Project table mode
         run: |
@@ -255,6 +258,32 @@ jobs:
           docker load --input /tmp/${{ env.IMAGE }}.tar
           docker compose up -d
           sleep 30
+
+      - name: Wait for Open Runtimes
+        run: |
+          max_attempts=180
+          attempt=0
+          success=0
+          while [ $attempt -lt $max_attempts ]; do
+              command="curl -s \$_APP_EXECUTOR_HOST/health -H \"Authorization: Bearer \$_APP_EXECUTOR_SECRET\""
+              response=$(docker compose exec appwrite sh -c "$command")
+
+              if [[ $response == *"runtimes"* ]]; then
+                  success=1
+                  break
+              else
+                  echo "Health check failed, retrying..."
+                  sleep 1
+                  ((attempt++))
+              fi
+          done
+
+          if [ $success -eq 0 ]; then
+              echo "Failed to start Open Runtimes executor"
+              exit 1
+          fi
+
+          echo "Open Runtimes executor started"
 
       - name: Run ${{ matrix.service }} tests with ${{ matrix.tables-mode }} table mode
         run: |
